packages:
  - "apps/**"
  - "packages/**"

nodeVersion: "26.2.0"
engineStrict: true

linkWorkspacePackages: true
saveWorkspaceProtocol: "rolling"
savePrefix: ""

publicHoistPattern:
  - "*eslint*"
  - "*@eslint*"
  - "*prettier*"
  - "*lint-staged*"
  - "*stylelint*"
  - "*commitlint*"
  - "*@commitlint*"
  - "*cz*"
  - "*simple-git-hooks*"
  - "*changeset*"

catalog:
  "@types/node": "^25.9.3"
  "npm-run-all2": "^9.0.2"
  "rimraf": "^6.1.3"
  "typescript": "^6.0.3"
  "zod": "^4.4.3"
  "dayjs": "^1.11.21"
  "vite": "^8.0.16"

catalogs:
  "dx":
    "@commitlint/cli": "^21.0.2"
    "@commitlint/config-conventional": "^21.0.2"
    "@commitlint/types": "^21.0.1"
    "czg": "^1.13.1"
    "lint-staged": "^17.0.7"
    "prettier": "^3.8.4"
    "simple-git-hooks": "^2.13.1"
    "@unconfig/ts-config-latest": "^0.0.1"
    "tsx": "^4.22.4"
    "turbo": "^2.9.14"
    "@manypkg/get-packages": "^3.1.0"

allowBuilds:
  esbuild: true
  simple-git-hooks: true
